### ISSUE TITLE
Visual Genome Train Test Splits

### ISSUE THREAD

**Issue by ymt123** [Lab41/attalos#23]
Create train/test splits for visual_genome.

Create a histogram of train/test/split classes to ensure we aren't introducing bias

**Comment by karllab41** [comment]
1. Hash function supposedly takes care of bias. This is traditionally taken care of through randomization, but you believe it will occur through the hash function naturally.

2. Per our discussion today, it is best to define these splits through lists, since that will provide us with additional flexibility. Included in our file structure are file lists anyway. (This may also be where Domino could help us, where we add the file lists to the project for replicability.)
